version: 2.1

orbs:
  orb-tools: circleci/orb-tools@7.3.0

workflows:
  lint_validate_publish-dev:
    jobs:
      - orb-tools/lint:
          name: lint
          lint-dir: src
          filters:
            tags:
              only:
                - /.*/
      - orb-tools/pack:
          name: pack-validate
          requires:
            - lint
          filters:
            tags:
              only:
                - /.*/
      - orb-tools/publish-dev:
          name: publish-dev
          orb-name: zachchai/docker
          context: orb_publish
          requires:
            - pack-validate
          filters:
            branches:
              only:
                - master
            tags:
              ignore:
                - /.*/
      - orb-tools/publish:
          name: publish
          orb-ref: zachchai/docker@$CIRCLE_TAG
          context: orb_publish
          validate: false
          attach-workspace: true
          checkout: false
          requires:
            - pack-validate
          filters:
            tags:
              only:
                - /.*/
            branches:
              ignore:
                - /.*/
